import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Orbitron } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const orbiton = Orbitron({
  subsets: ["latin"],
  variable: "--default-font",
  weight: "800",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${orbiton.className} `}>
      <body>{children}</body>
    </html>
  );
}
